### ISSUE TITLE
Wondering why triggers are updated with overwrite set to false

### ISSUE THREAD

**Issue by zachschultz** [apache/incubator-openwhisk-wskdeploy#305] opened 2017-08-07 20:59 UTC
I have a wskdeploy manifest yaml file that looks like:

```
package:
  name: messagehub-trigger
  version: 1.0
  license: Apache-2.0
  namespace: _
  dependencies:
    openwhisk-messagehub:
      location: /whisk.system/messaging
      inputs:
        kafka_brokers_sasl: $KAFKA_BROKERS
        user: $MESSAGEHUB_USER
        password: $MESSAGEHUB_PASS
        kafka_admin_url: $KAFKA_ADMIN_URL
  actions:
    process-message:
      location: actions/process-message.js
  triggers:
    message-received-trigger:
      source: openwhisk-messagehub/messageHubFeed
      inputs:
        isJSONData: true
        topic: $KAFKA_TOPIC
  rules:
      log-message-rule:
        trigger: message-received-trigger
        action: messagehub-trigger/process-message
```

When I changed the `source` of the `message-received-trigger` and ran wskdeploy I noticed that OpenWhisk didn't actually change the trigger, and after running with `verbose` I saw that the request was:

```
REQUEST:
[PUT]	https://openwhisk.ng.bluemix.net:443/api/v1/namespaces/_/triggers/message-received-trigger?overwrite=false
```

Why is it that everything else is sent with `overwrite=true` but trigger creations are sent with `overwrite=false`?

**Comment by zachschultz** [comment] 2017-08-07 21:11
It looks like the relevant code is here and that trigger feed actions are treated differently: https://github.com/apache/incubator-openwhisk-wskdeploy/blob/a67e7285845828510c2c6c8849c950c37ca4576d/deployers/servicedeployer.go#L415

**Comment by csantanapr** [comment] 2017-08-07 21:46
I think the wskdeploy needs to do more with feed actions to be able to updated them, it needs to delete the trigger and invoke the feed action with the with delete lifecycle, and then follow with normal feed creation.

**Comment by daisy-ycguo** [comment] 2017-08-23 01:49
@zachschultz You are right, I think it should be set to false.
```
_, _, err := deployer.Client.Triggers.Insert(t, false)
```

**Comment by daisy-ycguo** [comment] 2017-08-23 07:30
@zachschultz There is a PR #377 to address this issue. But I'm very curious to your case. What's the new value you want to update the `source` of the `message-received-trigger`?

**Comment by zachschultz** [comment] 2017-08-23 18:43
Hi @daisy-ycguo, thanks for the PR! What was happening for us was that if we changed our manifest.yaml file to change the trigger in any way, no updates were actually propagating through because of the `overwrite=false`

**Comment by mrutkows** [comment] 2017-08-23 18:53
@zachschultz can u verify if PR 337 allows this issue to be resolved?

**Comment by zachschultz** [comment] 2017-08-23 20:05
@mrutkows let me build a wskdeploy with that PR included to test if it works

**Comment by daisy-ycguo** [comment] 2017-08-28 02:23
@zachschultz Are we able to close it ?

**Comment by zachschultz** [comment] 2017-08-28 21:59
@daisy-ycguo On my most recent run with the new binary I now see this error `Got error creating trigger with error message: A trigger feed is only permitted when the trigger is created (code 162316) and error code: 144.`

**Comment by daisy-ycguo** [comment] 2017-08-29 08:09
@zachschultz please make sure the environment variables are setting to correct values. When I met with this error, it means feed `openwhisk-cloudant/changes` is not created successfully, which is caused by missing environment variables.
```
export CLOUDANT_HOSTNAME=f24a57b7-bluemix.cloudant.com
export CLOUDANT_USERNAME=f24a57b7-bluemix
export CLOUDANT_PASSWORD=24b84123bd42b1d3e4858af72576984
export CLOUDANT_DATABASE=cats
```

**Comment by mrutkows** [comment] 2017-08-30 02:30
Fixed in https://github.com/apache/incubator-openwhisk-wskdeploy/pull/377

**Closed by mrutkows** 2017-08-30 02:30 UTC
Labels: bug, priority: critical
