### ISSUE TITLE
Cannot specify nodejs:default runtime

### ISSUE THREAD

**Issue by asteed** [apache/incubator-openwhisk-wskdeploy#1032] opened 2019-02-15 22:22 UTC
## Overview
Currently it appears that the runtime specified in the `manifest.yml` has to be an explicit runtime version (e.g.: `nodejs:8`). It does not support using the value `nodejs:default`.
## Example
Given the following `manifest.yml`
```yaml
packages:
  myPackage:
    version: 0.0.5
    license: Apache-2.0
    public: false
    actions:
      myAction:
        location: ./my-package-action.zip
        runtime: nodejs:default
```
The result when using `wskdeploy` is as follows
```
$ wskdeploy        
Info: The API host is [http://localhost:8888], from .wskprops.
Info: The auth key is set, from .wskprops.
Info: The namespace is [whisk.system], from .wskprops.
Info: Unmarshal OpenWhisk runtimes from internet at http://localhost:8888.
Error: manifestreader.go [93]: [ERROR_YAML_FILE_FORMAT_ERROR]: File: [manifest.yml]: 
==> manifest_parser.go [738]: [ERROR_YAML_INVALID_RUNTIME]: File: [manifest.yml]: Invalid or missing runtime [nodejs:default] specified in manifest for the action [myAction].
==> Action [myAction]: Runtime [nodejs:default]: Supported Runtimes [ruby:2.5, swift:3.1.1, swift:4.1, swift:4.2, nodejs:6, nodejs:8, nodejs:10, java, go:1.11, php:7.2, php:7.3, python, python:2, python:3, dotnet:2.2]
==> 
```
Below is the list of available runtimes where `nodejs:6` is currently indicated as the default nodejs runtime.
```
→ curl -s "http://localhost:8888" | jq '.runtimes.nodejs'
[
  {
    "attached": false,
    "default": true,
    "deprecated": false,
    "image": "openwhisk/nodejs6action:latest",
    "kind": "nodejs:6",
    "requireMain": false
  },
  {
    "attached": false,
    "default": false,
    "deprecated": false,
    "image": "openwhisk/action-nodejs-v8:latest",
    "kind": "nodejs:8",
    "requireMain": false
  },
  {
    "attached": false,
    "default": false,
    "deprecated": false,
    "image": "openwhisk/action-nodejs-v10:latest",
    "kind": "nodejs:10",
    "requireMain": false
  }
]
```

**Comment by TPei** [comment] 2019-02-18 05:36
Hmm, it actually works on my machine

**Comment by TPei** [comment] 2019-02-18 05:46
I assume you are running the latest version of wskdeploy?

**Comment by asteed** [comment] 2019-02-19 15:55
Hi @TPei - Yes, this was initially done with 0.9.9
```
→ wskdeploy version
wskdeploy version: 0.9.9
```
I've also just tested the unnumbered `latest` [version](https://github.com/apache/incubator-openwhisk-wskdeploy/releases/download/latest/openwhisk_wskdeploy-latest-mac-amd64.zip) (that shows it was modified yesterday) and see the same result.

Both fail with the same output
```
Error: manifestreader.go [93]: [ERROR_YAML_FILE_FORMAT_ERROR]: File: [manifest.yml]: 
==> manifest_parser.go [735]: [ERROR_YAML_INVALID_RUNTIME]: File: [manifest.yml]: Invalid or missing runtime [nodejs:default] specified in manifest for the action [myAction].
==> Action [myAction]: Runtime [nodejs:default]: Supported Runtimes [php:7.2, php:7.3, python, python:2, python:3, dotnet:2.2, ruby:2.5, swift:3.1.1, swift:4.1, swift:4.2, nodejs:6, nodejs:8, nodejs:10, java, go:1.11]
```
If it helps, I'm running openwhisk via docker-compose based off latest master.

**Comment by TPei** [comment] 2019-02-20 10:25
Ok, I was able to reproduce this, it was working for me earlier since I tried it with a source file (not a zip) and it just inferred the runtime in that case and set to latest...

**Comment by TPei** [comment] 2019-02-20 11:24
Ok, I first of all added a test for this:
https://github.com/apache/incubator-openwhisk-wskdeploy/pull/1039
and as expected it throws the same error:
https://travis-ci.org/apache/incubator-openwhisk-wskdeploy/builds/495929157

Next up would be a fix, but I'm not sure my knowledge suffices to do this :laughing:

So we might need some help here from @pritidesai or @mrutkows :smiley:

**Comment by rabbah** [comment] 2019-02-21 16:36
Here's my guess: the runtimes are set by reading the manifest from the API host. This list does not include a "default" kind. That has to be constructed based on the response which looks like this:

```
{
  "runtimes": {
     "ballerina": [{"attached":true,"default":true,"deprecated":false,"image":"openwhisk/action-ballerina-v0.990.2:0f7df9c","kind":"ballerina:0.990","requireMain":false}],
     ...
  }
}
```

One has to map over the runtimes and find the default.
Alternatively, wskdeploy should just assume that `:default` always exists and just check that there exists a kind family matching the specified kind.

**Comment by rabbah** [comment] 2019-02-21 16:37
I think this is the relevant method: https://github.com/apache/incubator-openwhisk-wskdeploy/blob/755d4a4ec2e283e4d0b958a8db9c8a1d3a6a13c9/cmd/root.go#L123-L133

**Comment by TPei** [comment] 2019-02-22 07:27
thanks @rabbah I'll look into that :)

**Comment by TPei** [comment] 2019-03-06 05:40
Hey @asteed
#1039 was merged yesterday and it seems to be working now if you use the new, latest release
https://github.com/apache/incubator-openwhisk-wskdeploy/releases/tag/latest

**Closed** 2019-03-06 13:03 UTC
